apiVersion: v1
kind: PersistentVolume
metadata:
  name: example-pv
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-0d6c34fc740ad3933
