apiVersion: v1 
kind: ReplicationController
metadata:
  name: rc-test
  labels:
    type: rc 
spec: ## specific to RC
  replicas: 5 ## no of pod to create 
  selector:
    type: create 
  template: #### The below statements belongs to pod.
    metadata:
      name: mypod
      labels:
        type: create 
    spec: ## specific to pod 
      containers:
      - name: httpd
        image: httpd:latest
        ports:
        - containerPort: 80
