apiVersion: v1
kind: Pod
metadata:
  name: with-node-affinity-hard-anti
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: tier
            operator: NotIn
            values:
            - web
  containers:
  - name: with-node-affinity
    image: malleshdevops/devopseks17:reactjs-v2
  imagePullSecrets:
  - name: doc-pvt-cred

