apiVersion: v1
kind: Pod
metadata:
  name: nginx-label-demo-anit-affinity
spec:
  containers:
  - name: nginx
    image: nginx
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: type
            operator: In
            values:
            - create
        topologyKey: kubernetes.io/hostname
