apiVersion: v1
kind: Pod
metadata:
  name: nginx-label-demo-1
spec:
  containers:
  - name: nginx
    image: nginx
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: type
            operator: In
            values:
            - create
        topologyKey: kubernetes.io/hostname
