apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-claim-dynamic-gp3
spec:
  storageClassName: "gp3" # Empty string must be explicitly set otherwise default StorageClass will be set
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
